# Generated by Django 2.1.8 on 2020-04-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('client', models.CharField(max_length=64, verbose_name='客户端')),
                ('score', models.IntegerField(verbose_name='分数')),
            ],
        ),
    ]
